pool: Hosted Windows 2019 with VS2019

steps:

- checkout: self

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c Release'
    configuration: 'Release'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '-c Release'
    configuration: 'Release'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    configuration: 'Release'
    feedsToUse: 'select'
    packagesToPack: 'LongRunner/LongRunner.csproj'
    nobuild: true
    versioningScheme: 'off'