pool: Hosted Windows 2019 with VS2019

steps:

- checkout: self

- task: DotNetCoreCLI@2
  name: 'Build'
  inputs:
    command: 'build'
    arguments: '-c Release'
    configuration: 'Release'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  name: 'Tests'
  inputs:
    command: 'test'
    arguments: '-c Release'
    configuration: 'Release'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    feedsToUse: 'select'
    packagesToPack: '**/*.csproj'
    configuration: 'Release'
    versioningScheme: 'byBuildNumber'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'cyaspik'
    versioningScheme: 'off'