pool: Hosted Windows 2019 with VS2019
name: 1.0.0$(Rev:.r)

steps:

- checkout: self

- task: NuGetToolInstaller@1
  name: 'EnsureLatestNuGetTools'
  inputs:
    versionSpec: 
    checkLatest: true

- task: DotNetCoreCLI@2
  name: 'Build'
  inputs:
    command: 'build'
    arguments: '-c Release'
    configuration: 'Release'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: VSTest@2
  name: 'Tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '*/bin/*/*/*.Tests.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true
    runSettingsFile: 'Production.runsettings'

- task: NuGetCommand@2
  name: 'Pack'
  inputs:
    command: 'pack'
    feedsToUse: 'select'
    packagesToPack: 'LongRunner/*.csproj'
    configuration: 'Release'
    packDestination: '$(Build.ArtifactStagingDirectory)/packages'
    versioningScheme: 'byBuildNumber'

- task: PublishBuildArtifacts@1
  name: 'PublishArtifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/packages'
    ArtifactName: 'packages'
    publishLocation: 'Container'