queue: Hosted VS2017

steps:

- checkout: self
  clean: true

- task: MSBuild@1
  displayName: Restore
  inputs:
    solution: LongRunner.sln
    msbuildArguments: /t:Restore /p:Configuration=Release /m

- task: MSBuild@1
  displayName: Build
  inputs:
    solution: LongRunner.sln
    msbuildArguments: /p:PackOnBuild=true /p:Configuration=Release

- task: VSTest@2
  displayName: Test
  inputs:
    testAssemblyVer2: LongRunner.Tests\bin\*\*\*.Tests.dll
    diagnosticsEnabled: false
    rerunFailedTests: false
