pool: Hosted Windows 2019 with VS2019

steps:

- checkout: self

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c Release'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '-c Release'
    feedsToUse: 'select'
    versioningScheme: 'off'
